name:  Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout repo
      uses: actions/checkout@v3

    - name:  Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name:  Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name:  Run Lint/Test (optional)
      run: echo "Add pytest or linting here"

    # Optional: Deploy to Render/Heroku/EC2
    # Add a deployment script or use a deploy action here
